"""snesrecomp.recompiler.v2.emit_bank

Bank-level emit driver: walks every cfg entry in one bank and emits a
complete C source file containing every function as a separate
`void bank_BB_AAAA(CpuState *cpu)` definition.

Replaces v1's per-bank emit driver (the call-site of `emit_function`
inside `recomp.py`'s top-level `main()`).

Public API:
    emit_bank(rom, bank, entries, *, file_name=None,
              mode_overrides=None) -> str

`entries` is a list of `BankEntry` records describing each function to
emit. The caller (cfg loader, in Phase 6c) is responsible for parsing
the cfg and building this list.
"""

import sys
import pathlib

_THIS_DIR = pathlib.Path(__file__).resolve().parent
_RECOMPILER_DIR = _THIS_DIR.parent
for p in (str(_THIS_DIR), str(_RECOMPILER_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

from dataclasses import dataclass  # noqa: E402
from typing import Dict, List, Optional, Tuple  # noqa: E402

from v2.emit_function import emit_function  # noqa: E402


@dataclass
class BankEntry:
    """One function to emit in this bank.

    Attributes:
        name: C function name (e.g. "I_RESET", "ProcessNormalSprites").
            If None, defaults to bank_BB_AAAA based on the start PC.
        start: 16-bit local PC, must be in $8000-$FFFF for LoROM.
        end: optional exclusive end PC. If None, decoder runs until
            terminators.
        entry_m, entry_x: entry mode-state. Default (1, 1) — 65816 reset
            state, which is what most SMW functions are entered with.
    """
    name: Optional[str]
    start: int
    end: Optional[int] = None
    entry_m: int = 1
    entry_x: int = 1


def emit_bank(rom: bytes, bank: int,
              entries: List[BankEntry],
              *,
              file_header: Optional[str] = None,
              dispatch_helpers=None,
              exclude_ranges: Optional[List[Tuple[int, int]]] = None) -> str:
    """Emit one bank's C source.

    Args:
        rom: full LoROM image (bytes).
        bank: 8-bit bank number.
        entries: list of BankEntry records — one per function.
        file_header: optional C header lines (includes, banner). If
            None, a default header is emitted.

    Returns:
        Complete C source file as a string. Caller writes it to disk.
    """
    if file_header is None:
        file_header = _default_file_header(bank)

    parts: List[str] = [file_header, ""]

    # Forward decls for every in-bank entry. Each entry emits at the
    # variant-mangled name (`Foo_M{m}X{x}`); calls to later-defined
    # functions need the suffixed declaration to satisfy C lookup.
    parts.append("/* Forward declarations for in-bank entries. */")
    for entry in entries:
        base = entry.name or _default_func_name_local(bank, entry.start)
        suffix = _variant_suffix(entry.entry_m, entry.entry_x)
        parts.append(f"void {base}{suffix}(CpuState *cpu);")
    parts.append("")

    for entry in entries:
        src = emit_function(
            rom=rom,
            bank=bank,
            start=entry.start,
            entry_m=entry.entry_m,
            entry_x=entry.entry_x,
            end=entry.end,
            func_name=entry.name,
            dispatch_helpers=dispatch_helpers,
            exclude_ranges=exclude_ranges,
        )
        parts.append(src)
        parts.append("")  # blank line between functions

    # Aliases for cfg-named entries — un-suffixed wrapper that calls
    # into one specific variant. Hand-written entry-point shims (e.g.
    # smw_rtl.c calling `I_RESET(&g_cpu)`) bind to these. The alias
    # picks the cfg-declared (entry_m, entry_x) — i.e. the canonical
    # entry for that name. If a function has multiple (m,x) variants
    # only one alias is emitted (the cfg-default); other variants are
    # reachable only through gen-emitted Call ops that mangle names.
    aliased: set = set()
    for entry in entries:
        if not entry.name:
            continue
        if entry.name in aliased:
            continue
        suffix = _variant_suffix(entry.entry_m, entry.entry_x)
        aliased.add(entry.name)
        parts.append(
            f"void {entry.name}(CpuState *cpu) {{ {entry.name}{suffix}(cpu); }}"
        )
    if aliased:
        parts.append("")

    return "\n".join(parts)


def _default_func_name_local(bank: int, start: int) -> str:
    return f"bank_{bank:02X}_{start:04X}"


def _variant_suffix(m: int, x: int) -> str:
    """Mirror of codegen._variant_suffix — duplicated to avoid the
    cross-module import cycle. Must stay in sync."""
    return f"_M{m & 1}X{x & 1}"


def _default_file_header(bank: int) -> str:
    return f"""\
/* Auto-generated by snesrecomp v2 emit_bank. Do NOT hand-edit.
 *
 * Bank ${bank:02X}. Each function below mutates the shared CpuState
 * struct via cpu->A / cpu->X / etc. Memory access goes through the
 * cpu_read{{8,16}} / cpu_write{{8,16}} helpers in cpu_state.h.
 */

#include "cpu_state.h"
#include "cpu_trace.h"
#include "funcs.h"
"""
